{
 "title": "MiWay",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gtfs_routes_active" }
   ]
  },
  {
   "title": "Headway (All Stops)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(gtfs_headway_seconds)" }
   ]
  },
  {
   "title": "Stops Skipped (By Route)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(gtfs_stop_skipped)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Vehicles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gtfs_vehicles_active" }
   ]
  },
  {
   "title": "Active Trips",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gtfs_trips_active" }
   ]
  },
  {
   "title": "Average Trip Delay (By Route)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "gtfs_trip_delay_seconds", "legendFormat": "{{route_id}}" }
   ]
  },
  {
   "title": "Trip On-Time Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(gtfs_trip_on_time_total) by (status)",
     "legendFormat": "{{status}} - {{route_id}}"
    }
   ]
  }
 ]
}